/*
 * generated by Xtext 2.22.0
 */
package de.dlr.coredsl.tablegen

import com.google.inject.Injector
import com.google.inject.Guice

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CoreDslGeneratorStandaloneSetup extends com.minres.coredsl.CoreDslStandaloneSetupGenerated {

    override Injector createInjector() {
        return Guice.createInjector(new CoreDslGeneratorModule());
    }
}
